version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.4
    container_name: voyago_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: voyago
    ports:
      - "5432:5432"
    volumes:
      - voyago_pgdata:/var/lib/postgresql/data

volumes:
  voyago_pgdata:
